#
##
# Main Makefile for glants
#
#  - Berlin Brown
#  bigbinc@hotmail.com
#
DIR = src/
PRG = glants

all:
	(cd $(DIR); make)
	(cp -f src/$(PRG) ./) 

clean:
	rm -f *~
	rm -f $(PRG)
	(cd $(DIR); make clean)
